### ISSUE TITLE
[Question] %playerlist_online,placeholder,yes,amount,||...%

### ISSUE THREAD

**Issue by Reimzon** [Tanguygab/PlayerList-PlaceholderAPI-Expansion#1]
Hello. I've been trying to figure out what I'm writing wrong for quite some time now. I tried writing the placeholder in {}, and in %%, and even in [], but nothing works. Also, I tried to mix them, but it still doesn't help. What am I doing wrong?

**Comment by Tanguygab** [comment]
the part before the || shouldn't have %%  [] or nothing, the second part though requires {} if you want to specify another placeholder, or just plain text  
You have an example here: https://github.com/Tanguygab/PlaceholderAPI-PlayerList-Expansion/wiki#examples

**Comment by Reimzon** [comment]
> the part before the || shouldn't have %% [] or nothing, the second part though requires {} if you want to specify another placeholder, or just plain text
> You have an example here: https://github.com/Tanguygab/PlaceholderAPI-PlayerList-Expansion/wiki#examples

Thank you for your help. I really made sure that this feature works, but it didn't help me.
If I try to check %playerlist_online,placeholder,yes,amount,vault_rank||yes%, it doesn't work (writes 0).
P.S.: At first I thought that I changed something wrong, but when I took the value from the example (player_is_op), it worked correctly.

**Comment by Tanguygab** [comment]
is your rank called "yes" ? because that's what you set it to be right now

**Comment by Reimzon** [comment]
> is your rank called "yes" ? because that's what you set it to be right now

Oh, sorry. 
I specified %playerlist_online,placeholder, yes, amount,vault_prefix||{vault_prefix}% and now it really works! Thank you!
