### ISSUE TITLE
how can I do %player_name%=!%player_name% check

### ISSUE THREAD

**Issue by d0ddn** [Tanguygab/PlayerList-PlaceholderAPI-Expansion#12]
I want to receive %playerlist_all_0% where there is no name of the player who called this command

For example, I have a list of players in the menu, I call them through %playerlist_all_0%, %playerlist_all_1%, etc. but in this listing I don't want to see the name of the player who calls this menu, how can I do this?

my cfg :
all:
        type: ONLINE
        included: true
        filters:
        - CANSEE
        - PLACEHOLDER:%plasmovoice_hasVoiceChat%=true
        - PLACEHOLDER:%player_name%=!%player_name%

**Comment by Tanguygab** [comment]
included: false

**Comment by d0ddn** [comment]
thx man <3
