### ISSUE TITLE
placeholder not equal filter

### ISSUE THREAD

**Issue by hkkongou** [Tanguygab/PlayerList-PlaceholderAPI-Expansion#9]
is there a way to do not equal? 
![image](https://github.com/Tanguygab/PlayerList-PlaceholderAPI-Expansion/assets/61608872/44d8087e-fb6d-4d0f-b280-3ee663d90918)

**Comment by Tanguygab** [comment]
not yet

**Comment by Tanguygab** [comment]
Now you can https://api.extendedclip.com/expansions/playerlist/
`- "!PLACEHOLDER:%vault_group%!=<groupName>"`
